### PR TITLE
Fix comment location marshalling in ClassModule

### LINKED ISSUE #1523: gem install --document=ri,rdoc causes error with rdoc 7.0.2 with undefined method 'empty?' for an instance of RDoc::Markup::Paragraph
With rdoc 7.0.2, the above `gem install --document=ri,rdoc` causes errors for some gems, like

```
[tasaka1@localhost ~]$ gem install -V hocon --document=ri,rdoc

.....
Installing ri documentation for hocon-1.4.0
Installing aliki documentation for hocon-1.4.0
ERROR:  While executing gem ... (NoMethodError)
    undefined method 'empty?' for an instance of RDoc::Markup::Paragraph

    return '' unless first_comment && !first_comment.empty?
                                                    ^^^^^^^
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/code_object/class_module.rb:713:in 'RDoc::ClassModule#search_snippet'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/generator/aliki.rb:151:in 'RDoc::Generator::Aliki#build_class_module_entry'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/generator/aliki.rb:80:in 'block in RDoc::Generator::Aliki#build_search_index'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/generator/aliki.rb:77:in 'Array#each'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/generator/aliki.rb:77:in 'RDoc::Generator::Aliki#build_search_index'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/generator/aliki.rb:109:in 'RDoc::Generator::Aliki#write_search_index'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/generator/aliki.rb:32:in 'RDoc::Generator::Aliki#generate'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/rubygems_hook.rb:149:in 'block in RDoc::RubyGemsHook#document'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/rubygems_hook.rb:146:in 'Dir.chdir'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/rubygems_hook.rb:146:in 'RDoc::RubyGemsHook#document'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/rubygems_hook.rb:205:in 'RDoc::RubyGemsHook#generate'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/rubygems_hook.rb:62:in 'block in RDoc::RubyGemsHook.generate'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/rubygems_hook.rb:61:in 'Array#each'
	/home/tasaka1/.local/share/gem/ruby/gems/rdoc-7.0.2/lib/rdoc/rubygems_hook.rb:61:in 'RDoc::RubyGemsHook.generate'
	/usr/share/rubygems/rubygems/request_set.rb:313:in 'block in Gem::RequestSet#install_hooks'
	/usr/share/rubygems/rubygems/request_set.rb:312:in 'Array#each'
	/usr/share/rubygems/rubygems/request_set.rb:312:in 'Gem::RequestSet#install_hooks'
	/usr/share/rubygems/rubygems/request_set.rb:210:in 'Gem::RequestSet#install'
	/usr/share/rubygems/rubygems/commands/install_command.rb:207:in 'Gem::Commands::InstallCommand#install_gem'
	/usr/share/rubygems/rubygems/commands/install_command.rb:223:in 'block in Gem::Commands::InstallCommand#install_gems'
	/usr/share/rubygems/rubygems/commands/install_command.rb:216:in 'Array#each'
	/usr/share/rubygems/rubygems/commands/install_command.rb:216:in 'Gem::Commands::InstallCommand#install_gems'
	/usr/share/rubygems/rubygems/commands/install_command.rb:162:in 'Gem::Commands::InstallCommand#execute'
	/usr/share/rubygems/rubygems/command.rb:326:in 'Gem::Command#invoke_with_build_args'
	/usr/share/rubygems/rubygems/command_manager.rb:253:in 'Gem::CommandManager#invoke_command'
	/usr/share/rubygems/rubygems/command_manager.rb:194:in 'Gem::CommandManager#process_args'
	/usr/share/rubygems/rubygems/command_manager.rb:152:in 'Gem::CommandManager#run'
	/usr/share/rubygems/rubygems/gem_runner.rb:57:in 'Gem::GemRunner#run'
	/usr/bin/gem:12:in '<main>'
```

I didn't see this issue with rdoc ~~6.7.0~~ 6.17.0 . Can this be fixed by ruby 4.0.0 release?

### PR DESCRIPTION
**Pull request by st0012**
Fixes #1523 

The issue is likely caused by RDoc generating documentation using data from marshal load (used by `ri`), which has different types than if the generation happen directly.

This code can reproduce the same error:

```rb
require 'rdoc'
require 'tmpdir'

# Setup store
options = RDoc::Options.new
store = RDoc::Store.new(options, path: Dir.tmpdir)

# Create a class with a comment
tl = store.add_file 'file.rb'
ns = tl.add_module RDoc::NormalModule, 'Namespace'
cm = ns.add_class RDoc::NormalClass, 'Klass', 'Super'
cm.add_comment 'This is a class comment', tl

# Before marshalling - works fine
puts "Before marshal: #{cm.search_snippet.inspect}"

# Marshal round-trip (simulates loading from .ri cache)
loaded = Marshal.load(Marshal.dump(cm))
loaded.store = store

# After marshalling - fails with NoMethodError
puts "After marshal: #{loaded.search_snippet.inspect}"
```

Similar to other code objects' marshalling behaviour, `ClassModule#comment_location`'s content type would change before/after marshalling. But it should still be an array of pairs that respond to the same set of methods.

This commit also adds documentation about the marshalling behaviour of `ClassModule#comment_location`.

I don't like the fact that data types & shapes could change before/after marshalling. But changing this design will be a breaking change and require some careful planning. So for now the change it to make sure the type change is less surprising

### CODE REVIEW

File: lib/rdoc/code_object/class_module.rb [hunk 1]
```diff
@@ -379,10 +394,10 @@ def marshal_load(array) # :nodoc:
 
     @comment    = RDoc::Comment.from_document document
 
-    @comment_location = if RDoc::Markup::Document === document.parts.first then
-                          document
+    @comment_location = if document.parts.first.is_a?(RDoc::Markup::Document)
+                          document.parts.map { |doc| [doc, doc.file] }
                         else
-                          RDoc::Markup::Document.new document
+                          [[document, document.file]]
```
Comment (vinistock) [inline lib/rdoc/code_object/class_module.rb:400]: We were creating a brand new document before. Was that intentional?

For example, should the updated code be this?

```ruby
new_doc = RDoc::Markup::Document.new document
[[new_doc, new_doc.file]]
```

Comment (tompng) [reply lib/rdoc/code_object/class_module.rb:400]: document is not a comment, so I think it should ideally be `[[comment, document.file]]` for both branch.
```ruby
@comment_locaation = [[comment, document.file]]
```

`parse([[@comment, document.file]])` will return a parsed document cached in `@comment` (as `attr_reader :document`)

Although not fully investigated the effect of doing this.

Comment (tompng) [reply lib/rdoc/code_object/class_module.rb:400]: Since `parse @comment_location` seems working, I'm OK with the less-impact change: `[[document, location]]` for now :+1:

**Review by tompng — APPROVED** [review]
