### PR TITLE
fix: C variables should never show up in Ancestors tree

### LINKED ISSUE #1205: In v6.8.1, C extension objects "Ancestors" list shows C symbol name instead of class name
Hi! I love the [ancestors list](https://github.com/ruby/rdoc/pull/1183), but I found an edge case with how it handles C extensions.

Take a look at the sidebar at https://nokogiri.org/rdoc/Nokogiri/HTML4/Document.html which was generated from 50dda134:

image

The actual ancestors list is:

```
Nokogiri::XML::Document
+- Nokogiri::XML::Node
   +- Object
      +- BasicObject
```

but instead it's showing `cNokogiriXmlNode` which is the C symbol that references the `Nokogiri::XML::Node` class (from `ext/nokogiri/xml_node.c`).

I haven't had time to dig into this yet, but wanted to raise an issue in case someone has the time to look.

### PR DESCRIPTION
**Pull request by flavorjones**
If a `NormalClass`'s superclass is a C variable ("enclosure"), then update the superclass to point to the RDoc::NormalClass.

This is done in a single pass after all files have been parsed.

Fixes #1205.

Before:

image

After:

image

### CODE REVIEW

File: lib/rdoc/store.rb [hunk 1]
```diff
@@ -197,6 +197,19 @@ def add_file absolute_name, relative_name: absolute_name, parser: nil
...
   end
 
+  ##
+  # Make sure any references to C variable names are resolved to the corresponding class.
+  #
+
+  def resolve_c_references
+    # superclass references
+    @classes_hash.each do |_, klass|
+      if String === klass.superclass && (candidate = find_c_enclosure(klass.superclass))
```
Comment (st0012) [inline lib/rdoc/store.rb:207]: nit:

```suggestion
    @classes_hash.each_value do |klass|
      if klass.superclass.is_a?(String) && (candidate = find_c_enclosure(klass.superclass))
```

File: lib/rdoc/store.rb [hunk 2]
```diff
@@ -197,6 +197,19 @@ def add_file absolute_name, relative_name: absolute_name, parser: nil
     top_level
   end
 
+  ##
+  # Make sure any references to C variable names are resolved to the corresponding class.
+  #
+
+  def resolve_c_references
```
Comment (st0012) [inline lib/rdoc/store.rb:204]: Will we need to resolve different types of references in the future? If we don't, `resolve_c_superclasses` may be better.

File: test/rdoc/test_rdoc_store.rb [hunk 3]
```diff
@@ -281,6 +281,26 @@ def test_find_c_enclosure_from_cache_legacy
...
+
+    @s.add_c_enclosure('cExternParent', parent)
+
+    # at this point, the child's superclass is still the name of the C variable
+    assert_equal("cExternParent", @s.classes_hash['Child'].superclass)
+
+    @s.resolve_c_references
+
+    # now the ancestor tree correctly references the NormalClass objects
+    assert_equal(parent, @s.classes_hash['Child'].superclass)
```
Comment (st0012) [inline test/rdoc/test_rdoc_store.rb:301]: (`#superclass` can return either string or `RDoc::NormalClass` really hurts my brain 🙈)

File: lib/rdoc/store.rb (hunk 1 above)
Comment (flavorjones) [reply lib/rdoc/store.rb:207]: 👍

File: lib/rdoc/store.rb (hunk 2 above)
Comment (flavorjones) [reply lib/rdoc/store.rb:204]: I'm not sure what else will end up with C variable names instead of classes, so I named it to be open-ended. But I'm happy to give it a narrower name (we can always rename it if we find we need to resolve more references later).

File: test/rdoc/test_rdoc_store.rb (hunk 3 above)
Comment (flavorjones) [reply test/rdoc/test_rdoc_store.rb:301]: 😬

**Review by st0012 — APPROVED** [review]
Thanks for the fix!

File: test/rdoc/test_rdoc_store.rb (hunk 3 above)
Comment (flavorjones) [reply test/rdoc/test_rdoc_store.rb:301]: And of course the bug in #1221 is related to this confusion. 🤦
