### PR TITLE
Fix broken legacy rdoc-ref labels and duplicate heading IDs

### LINKED ISSUE #1590: Duplicate id attributes
In the doc for [Regexp](https://docs.ruby-lang.org/en/master/Regexp.html), there are duplicate values for attribute `id`:

```
<span id="class-Regexp-label-Method+match" class="legacy-anchor"></span>
<h2 id="class-regexp-method-match"><a href="[#class-regexp-method-match](view-source:https://docs.ruby-lang.org/en/master/Regexp.html#class-regexp-method-match)">Method <code>match</code></a></h2>

<p>Each of the methods <a href="[Regexp.html#method-i-match](view-source:https://docs.ruby-lang.org/en/master/Regexp.html#method-i-match)"><code>Regexp#match</code></a>, <a href="[String.html#method-i-match](view-source:https://docs.ruby-lang.org/en/master/String.html#method-i-match)"><code>String#match</code></a>, and <a href="[Symbol.html#method-i-match](view-source:https://docs.ruby-lang.org/en/master/Symbol.html#method-i-match)"><code>Symbol#match</code></a> returns a <a href="[MatchData.html](view-source:https://docs.ruby-lang.org/en/master/MatchData.html)"><code>MatchData</code></a> object if a match was found, <code>nil</code> otherwise; each also sets <a href="[Regexp.html#class-regexp-global-variables](view-source:https://docs.ruby-lang.org/en/master/Regexp.html#class-regexp-global-variables)">global variables</a>:</p>

<pre class="ruby"><span class="ruby-string">&#39;food&#39;</span>.<span class="ruby-identifier">match</span>(<span class="ruby-regexp">/foo/</span>) <span class="ruby-comment"># =&gt; #&lt;MatchData &quot;foo&quot;&gt;</span>
<span class="ruby-string">&#39;food&#39;</span>.<span class="ruby-identifier">match</span>(<span class="ruby-regexp">/bar/</span>) <span class="ruby-comment"># =&gt; nil</span>
</pre>

<span id="class-Regexp-label-Operator+-3D~" class="legacy-anchor"></span>
<h2 id="class-regexp-operator-"><a href="[#class-regexp-operator-](view-source:https://docs.ruby-lang.org/en/master/Regexp.html#class-regexp-operator-)">Operator <code>=~</code></a></h2>

<p>Each of the operators <a href="[Regexp.html#method-i-3D~](view-source:https://docs.ruby-lang.org/en/master/Regexp.html#method-i-3D~)"><code>Regexp#=~</code></a>, <a href="[String.html#method-i-3D~](view-source:https://docs.ruby-lang.org/en/master/String.html#method-i-3D~)"><code>String#=~</code></a>, and <a href="[Symbol.html#method-i-3D~](view-source:https://docs.ruby-lang.org/en/master/Symbol.html#method-i-3D~)"><code>Symbol#=~</code></a> returns an integer offset if a match was found, <code>nil</code> otherwise; each also sets <a href="[Regexp.html#class-regexp-global-variables](view-source:https://docs.ruby-lang.org/en/master/Regexp.html#class-regexp-global-variables)">global variables</a>:</p>

<pre class="ruby"><span class="ruby-regexp">/bar/</span> <span class="ruby-operator">=~</span> <span class="ruby-string">&#39;foo bar&#39;</span> <span class="ruby-comment"># =&gt; 4</span>
<span class="ruby-string">&#39;foo bar&#39;</span> <span class="ruby-operator">=~</span> <span class="ruby-regexp">/bar/</span> <span class="ruby-comment"># =&gt; 4</span>
<span class="ruby-regexp">/baz/</span> <span class="ruby-operator">=~</span> <span class="ruby-string">&#39;foo bar&#39;</span> <span class="ruby-comment"># =&gt; nil</span>
</pre>

<span id="class-Regexp-label-Method+match-3F" class="legacy-anchor"></span>
<h2 id="class-regexp-method-match"><a href="[#class-regexp-method-match](view-source:https://docs.ruby-lang.org/en/master/Regexp.html#class-regexp-method-match)">Method <code>match?</code></a></h2>
```

### PR DESCRIPTION
**Pull request by st0012**
Decode legacy CGI-encoded labels (e.g., `What-27s+Here`) in rdoc-ref links so they resolve to the correct GitHub-style anchors. Also deduplicate heading IDs by appending -1, -2, etc. when multiple headings produce the same anchor (e.g., "Method match" and "Method match?" both becoming `method-match`).

Fixes #1590

### CODE REVIEW

File: test/rdoc/markup/to_label_test.rb [hunk 1]
```diff
@@ -111,4 +111,41 @@ def test_convert_tt
...
+    assert_equal "Foo::Bar", RDoc::Text.decode_legacy_label("Foo-3A-3ABar")
+  end
+
+  def test_decode_legacy_label_new_format_passthrough
+    assert_equal "Whats-Here", RDoc::Text.decode_legacy_label("Whats-Here")
+  end
+
+  def test_decode_legacy_label_alphanumeric_hex_unchanged
+    # -4F decodes to 'O' (alphanumeric), so leave as literal
+    assert_equal "class-4Fther", RDoc::Text.decode_legacy_label("class-4Fther")
```
Comment (tompng) [inline test/rdoc/markup/to_label_test.rb]: I think adding test case of something like `"class-Feather"` not to be converted to `"class\xFEather"` may help prevent regression.
This will detect a bug changing `/-([0-9A-F]{2})/`  to `/-([0-9A-Fa-f]{2})/` in the future

File: lib/rdoc/text.rb [hunk 2]
```diff
@@ -335,4 +335,27 @@ def wrap(txt, line_len = 76)
...
+  # encodes alphanumerics).
+  #
+  # Examples:
+  #   "What-27s+Here"  -> "What's Here"  (legacy: -27 is apostrophe)
+  #   "Foo-3A-3ABar"   -> "Foo::Bar"     (legacy: -3A is colon)
+  #   "Whats-Here"     -> "Whats-Here"   (new format, unchanged)
+
+  module_function def decode_legacy_label(label)
+    label = label.tr('+', ' ')
+    label.gsub!(/-([0-9A-F]{2})/) do
```
Comment (tompng) [inline lib/rdoc/text.rb]: If it's OK to assume encoded parts to be ascii, `/-([0-7][0-9A-F])/` might be better
