### PR TITLE
Fix rb_define_method(singleton_class_of_module, ...) not to change nested module name

### LINKED ISSUE #1440: Duplicate entries in "Class and Module Index"
These screenshots are from ruby/resolv.

Image

The opened trees are same too.
Image

I don't know what the trigger is, but I've sometimes seen the same problem for years.

### PR DESCRIPTION
**Pull request by tompng**
Fixes #1440
Always track class and singleton class stored to a variable to `@classes`.
Otherwise, `find_class var_name, class_name` called from `handle_method` will add a new class.

Before:
before
After:
after

Minimal reproduction:
```c
VALUE mFoo = rb_define_module("Foo");
VALUE mBar = rb_define_module_under(mFoo, "Bar");
VALUE mBarS = rb_singleton_class(mBar);
rb_define_method(mBarS, "baz", baz, 0);
```

`RDoc::Parser::C#handle_method` calls `find_class 'mBarS', 'Foo::Bar'`.
`RDoc::Parser::C#find_class` calls `@top_level.add_class RDoc::NormalClass, 'Foo::Bar'`. This will create `::Bar` for some reason and `Foo::Bar` disappears from generated document.

### CODE REVIEW

File: test/rdoc/parser/c_test.rb [hunk 1]
```diff
@@ -781,6 +781,41 @@ def test_do_methods_singleton_class
     assert               methods.first.singleton
   end
 
+
```
Comment (kou) [inline test/rdoc/parser/c_test.rb]:
```suggestion
```

**Review by kou — APPROVED** [review]
+1
