### PR TITLE
Fix incorrect method linking in `tt` tags

### LINKED ISSUE #1390: Backslash in RDoc monofont causes linking
Bug can be reproduced by generating the RDoc for this script:

```ruby
class Foo
  # This is not linked:
  # <tt>.bar.hello()</tt>
  #
  # But these are linked:
  # <tt>.bar.hello(\)</tt>
  # <tt>.bar.hello(\\\\)</tt>
  def foo

  # Hello from bar
  def bar
  end
end
```

The generated RDoc HTML looks like this. Notice how the backslash causes the monofont to generate a link to `Foo#bar`:

Image

I cannot find a way to prevent this link from generating. I think this is a bug, but I might be missing something from the syntax.

### PR DESCRIPTION
**Pull request by st0012**
Fix #1390

### CODE REVIEW

File: lib/rdoc/markup/to_html_crossref.rb [hunk 1]
```diff
@@ -184,43 +184,73 @@ def link(name, text, code = true, rdoc_ref: false)
...
   end
+
+  private
+
+  ##
+  # Detects <tt>...</tt> spans that contain a single cross-reference candidate.
+  # When the candidate occupies the whole span (aside from trailing
+  # punctuation), the tt markup is replaced by the resolved cross-reference.
+
+  def convert_tt_crossref(flow, index)
```
Comment (kou) [inline lib/rdoc/markup/to_html_crossref.rb]: Should we use `flow_items` here too?

File: test/rdoc/rdoc_markup_to_html_crossref_test.rb [hunk 2]
```diff
@@ -33,6 +33,33 @@ def test_convert_CROSSREF
...
+    result = formatter.convert '<tt>.bar.hello(\)</tt>'
+
+    assert_equal para('<code>.bar.hello(\)</code>'), result
+
+    formatter = RDoc::Markup::ToHtmlCrossref.new @options, 'C9.html', @c9_b
+    result = formatter.convert '<tt>.bar.hello(\\\\)</tt>'
+
+    assert_equal para('<code>.bar.hello(\\)</code>'), result
+  ensure
+    @options.hyperlink_all = hyperlink_all
```
Comment (kou) [inline test/rdoc/rdoc_markup_to_html_crossref_test.rb]: It seems that we don't need this because we always set `@options.hyperlink_all` in `setup`.

File: test/rdoc/rdoc_markup_to_html_crossref_test.rb [hunk 3]
```diff
@@ -33,6 +33,33 @@ def test_convert_CROSSREF
     assert_equal para("<code># :stopdoc:</code>:"), result
   end
 
+  def test_convert_CROSSREF_backslash_in_tt
+    hyperlink_all = @options.hyperlink_all
+    @options.hyperlink_all = false
+
+    formatter = RDoc::Markup::ToHtmlCrossref.new @options, 'C9.html', @c9_b
+    result = formatter.convert '<tt>C1</tt>'
+
```
Comment (kou) [inline test/rdoc/rdoc_markup_to_html_crossref_test.rb:40]: How about removing this empty line because `format = ...; result = ...; assert_equal ...` are related?

```suggestion
```

**Review by kou — APPROVED** [review]
+1

File: test/rdoc/rdoc_markup_to_html_crossref_test.rb (hunk 3 above)
Comment (st0012) [reply test/rdoc/rdoc_markup_to_html_crossref_test.rb:40]: I've reduced the lines this test takes
